### ISSUE TITLE
希望可以加入正统道藏

### ISSUE THREAD

**Issue by zhenruyan** [chinese-poetry/chinese-poetry#118]

**Comment by xjr7670** [comment]
不同意，虽然我也是个道家思想的推崇者。这是诗词总汇，把道藏加进来不合适，而且加了道藏，后面可能有人还会提议把佛经也加一下，然后各种。。元曲、明清小说。。。有需要的建议去专门的网站看一下，比如道教之音、中国哲学书电子化计划

**Comment by O70** [comment]
可以新起一个仓库一起来整整

**Comment by zhenruyan** [comment]
> 不同意，虽然我也是个道家思想的推崇者。这是诗词总汇，把道藏加进来不合适，而且加了道藏，后面可能有人还会提议把佛经也加一下，然后各种。。元曲、明清小说。。。有需要的建议去专门的网站看一下，比如道教之音、中国哲学书电子化计划

额。我的意思也是 新建一个仓库

**Comment by xjr7670** [comment]
> > 不同意，虽然我也是个道家思想的推崇者。这是诗词总汇，把道藏加进来不合适，而且加了道藏，后面可能有人还会提议把佛经也加一下，然后各种。。元曲、明清小说。。。有需要的建议去专门的网站看一下，比如道教之音、中国哲学书电子化计划
> 
> 额。我的意思也是 新建一个仓库

那我是赞成的，并且乐意提供 PR😁
