### ISSUE TITLE
增加诗经数据

### ISSUE THREAD

**Issue by jackeyGao** [chinese-poetry/chinese-poetry#12]
https://zh.wikipedia.org/wiki/%E8%AF%97%E7%BB%8F

> 《诗经》是中国最早的诗歌总集，溯自公元前11到前6世纪，原本叫《诗》，共有诗歌305首（除此之外还有6篇有题目无内容,即有目无辞，称为笙诗六篇，题目分别是南陔、白华、华黍、由庚、崇丘和由仪）[1]，又称《诗三百》。[2]从汉朝起儒家将其奉为经典，遂也称之谓《诗经》，而正式使用《诗经》一名，应该起于南宋初年[3]。早期诗经版本众多，其中最为著名也是流传至今的，是汉朝毛亨、毛苌注释的《诗经》，因此该版本又称为《毛诗》。《诗经》中的诗的作者，绝大部分已经无法考证。其所涉及的地域，主要是黄河流域，西起山西和甘肃东部，北到河北省西南，东至山东，向南也远及江汉流域。  --------- 维基百科

**数据源要求**

- 来源可靠
- 便于抓取
- 数目接近305首
- 有“四始六义”、音乐、表现手法分类
- 由于作者大多无法考证， 统一不记作者。

**Comment by snowtraces** [comment]
#64
