### ISSUE TITLE
涵盖范围有约束么

### ISSUE THREAD

**Issue by caukie** [chinese-poetry/chinese-poetry#128]
看到有 幽梦影， 那这个就变成古籍文库了吧。
本人比较喜欢元曲，不知道怎么加入

**Comment by jackeyGao** [comment]
元曲我个人认为可以加入， 欢迎提供 PR.

我个人认为只对宗教的文献有约束。 

比如后续如果有佛教的经文或者其他宗教的著作， 可能会被禁止。
