### ISSUE TITLE
打赏网站无法访问

### ISSUE THREAD

**Issue by richarddong** [chinese-poetry/chinese-poetry#129]
https://jackeygao.io/donation.html

我在加州 无法访问 😛

**Comment by jackeyGao** [comment]
谢谢 😀， 

我的域名到期， 改为 https://ijg.io， 但没有赞赏页面了， 这个项目准备使用 opencollective 来接受捐赠支持， 这样做会更加透明点。  

我会最近时间看下 opencollective 的捐赠形式以及条款， 然后有空加上去。
