### ISSUE TITLE
我花了2个星期开发了一套含80万首诗词的APP,欢迎观摩体验

### ISSUE THREAD

**Issue by qq475742653** [chinese-poetry/chinese-poetry#139]
博客地址：http://www.headset.xin
APP安卓安装包:http://www.headset.xin/tangsongsc/tangsongsc.apk
h5演示地址：http://www.headset.xin/tangsongsc

**Comment by lihao6666** [comment]
可以提供下数据吗

**Comment by Lordyoung-cpp** [comment]
用户许可协议认真的？

**Comment by qq475742653** [comment]
> 用户许可协议认真的？
-----------
 不好意思，做的有点赶。已修复了用户协议。

**Comment by Lordyoung-cpp** [comment]
> > 用户许可协议认真的？
> 
> 不好意思，做的有点赶。已修复了用户协议。

还是没有完整，不过大体上OK
另，发送彩信、使用摄像头、录音、读取位置信息是用来干嘛的？

**Comment by qq475742653** [comment]
> > > 用户许可协议认真的？
> > 
> > 
> > 不好意思，做的有点赶。已修复了用户协议。
> 
> 还是没有完整，不过大体上确定
> 另，发送彩信，使用摄像头，录音，读取位置信息是用来干嘛的？
-------------
 发送彩信是注册用户时所需，不过已用第三方服务的WEBAPI注册了，cordoval插件应该用不到。只是提示开这个权限，不允许时，也不影响系统注册使用。
摄像头和录音，是为了用户在评论、补充诗词时使用，因为读背诗词的精要在于“令人感悟、感受美好、在后人遇相同场景和际遇时激发记忆中的诗词，从而有感而发“，故可通过APP上传录音，如诗词之吟颂、场景之声、现场美图、名师视频讲解等。
读取位置，是为了记录用户补充诗词时，在外拍照时位置，便于风景名胜位置定位。用的是百度的API，即使用户调为高精度GPS，也有一定误差，但这样就不敏感了。貌似用户禁用应用的定位，也不影响经纬度度、市、区街道的获取。
