### ISSUE TITLE
建议去掉诗的 strains 

### ISSUE THREAD

**Issue by zhongwencm** [chinese-poetry/chinese-poetry#149]
1.  现在的都是自动生成的.有需要的自己生成即可
2.  现在诗有一些错误. 导致平仄也有一些错误
3.  平仄本身也有错误

导致一些问题.  修正诗的时候.要另外修正平仄.  反正都是自动生成的. 错误又多. 删掉比较好.

**Comment by zhongwencm** [comment]
@jackeyGao

**Comment by jackeyGao** [comment]
收到， 看起来平仄可以通过程序生成， 如果可以我们可以在主文件去除格律， 来精简内容。 我相信这是一个好的方向， 但为了过渡 我建议在其他文件中通过 id 引用的形式保留格律， 观察一段时间没有人使用和维护， 我们就计划移从仓库除掉这个文件。 这样做，是否可以？

**Comment by xinglie** [comment]
我觉得可行，一定要保持主文件的精简，其它信息可以通过附加的形式给到有需求的人员，回头我来删除主文件中的平仄，然后把平仄转移到其它文件夹中吧
