### ISSUE TITLE
SELECT * FROM ci WHERE author='李白' 为啥搜不到呢

### ISSUE THREAD

**Issue by buzai** [chinese-poetry/chinese-poetry#16]
SELECT * FROM ci WHERE author='李白' 这样搜搜不到李白？

cat ./josn/* | grep '李白' 有李白的数据

SELECT * FROM ci WHERE author='辛弃疾' 这个就可以找到。。我也是醉了

**Comment by jackeyGao** [comment]
json 文件是唐诗体， ci.db 中存储的是2w多的宋词. 全唐诗仅 json 分发.

**Comment by buzai** [comment]
搜噶明白了。我想把他们转入到mysql里都
