### ISSUE TITLE
词中大量生僻字缺失

### ISSUE THREAD

**Issue by snowtraces** [chinese-poetry/chinese-poetry#161]
看到这个([补全陆游《钗头凤》缺字](https://github.com/chinese-poetry/chinese-poetry/commit/c720759d7f523d83bddb0b46d7b1710fe9c11d81))commit，猜想ci文件夹下有其它文字缺失的问题，于是通过词牌名归类对比长度来判断缺字问题，发下大量生僻字缺失

以词牌名《鹧鸪天》为例，文件`ci.song.1000.json`长度对比如下图：

![鹧鸪天长度对比](https://user-images.githubusercontent.com/21019407/69850757-f319e900-12ba-11ea-8739-f394abd9a3f5.jpg)

![鹧鸪天长度对比_diff](https://user-images.githubusercontent.com/21019407/69850980-98cd5800-12bb-11ea-8488-d2954a90e952.jpg)

**Comment by snowtraces** [comment]
手动处理很花时间，写查询自动处理，以搜索引擎结果作为候选，人工审阅可能会更好
[对比文件](https://github.com/snowtraces/chinese-poetry/blob/6a87ba2ed14084e567074ffae11113c7ffe0aa2f/ci/%E8%AF%8D%E7%89%8C%E5%90%8D%E5%BD%92%E7%B1%BB%E9%95%BF%E5%BA%A6%E5%AF%B9%E6%AF%94.json)

**Comment by jackeyGao** [comment]
👍这个方法不错，

```
 "0": {
      "272": "7-5#3-7-3#5-5-5#3-7-3#5",
      "285": "7-5#3-7-3#3#3-5-5#3-7-3#3#3",
      "374": "7-5#3-7-3#3#3-5-5#3-7-3#3#3"
    },
    "2000": {
      "234": "5#4-7-3#6-5#3-4#4-7-4#6-5#3",
      "235": "5#4-7-4#6-5#3-4#4-7-4#6-5#3",
      "247": "5#4-7-4#6-5#3-4#4-7-4#6-5#3",
      "248": "5#4-7-4#6-5#3-4#4-7-4#6-5#3",
      "249": "5#4-7-4#6-5#3-4#4-7-4#6-5#3",
      "250": "5#4-7-4#6-5#3-4#4-7-4#6-5#3",
      "251": "5#4-7-4#6-5#3-4#4-7-4#6-5#3",
      "252": "5#4-7-4#6-5#3-4#4-7-4#6-5#3",
      "253": "5#4-7-4#6-4#3-4#4-7-4#6-5#3",
      "254": "5#4-7-4#6-5#3-4#4-7-4#6-5#3"
    },
```

请问， 这里的 `0`和`2000` 是文件名， `272`和`234` 是文件里诗词的索引吗？

**Comment by snowtraces** [comment]
对的

**Comment by snowtraces** [comment]
> 👍这个方法不错，
> 
> ```
>  "0": {
>       "272": "7-5#3-7-3#5-5-5#3-7-3#5",
>       "285": "7-5#3-7-3#3#3-5-5#3-7-3#3#3",
>       "374": "7-5#3-7-3#3#3-5-5#3-7-3#3#3"
>     },
>     "2000": {
>       "234": "5#4-7-3#6-5#3-4#4-7-4#6-5#3",
>       "235": "5#4-7-4#6-5#3-4#4-7-4#6-5#3",
>       "247": "5#4-7-4#6-5#3-4#4-7-4#6-5#3",
>       "248": "5#4-7-4#6-5#3-4#4-7-4#6-5#3",
>       "249": "5#4-7-4#6-5#3-4#4-7-4#6-5#3",
>       "250": "5#4-7-4#6-5#3-4#4-7-4#6-5#3",
>       "251": "5#4-7-4#6-5#3-4#4-7-4#6-5#3",
>       "252": "5#4-7-4#6-5#3-4#4-7-4#6-5#3",
>       "253": "5#4-7-4#6-4#3-4#4-7-4#6-5#3",
>       "254": "5#4-7-4#6-5#3-4#4-7-4#6-5#3"
>     },
> ```
> 
> 请问， 这里的 `0`和`2000` 是文件名， `272`和`234` 是文件里诗词的索引吗？

对的

**Comment by ulyanovsk** [comment]
词牌名相同，并不一定格式一样，我专门查了，词牌名有变体。大佬们可能还要想其他方式来解决。
但集思广益的基础，要在每个诗词加上UUID，不然不好汇总啊，希望在词的内容上加上uuid，作者也是（生平的纰漏汇总）

**Comment by snowtraces** [comment]
> 词牌名相同，并不一定格式一样，我专门查了，词牌名有变体。大佬们可能还要想其他方式来解决。
> 但集思广益的基础，要在每个诗词加上UUID，不然不好汇总啊，希望在词的内容上加上uuid，作者也是（生平的纰漏汇总）

格式是不一定相同，但是通过对比还是一个方便的机制。
我昨天更了一次补全，没有使用这种方法对比，通过第三方数据，通过去除停用词后对比长度，逐句对比长度进行补全
