### ISSUE TITLE
宋词数据库 作者 长简介有重复

### ISSUE THREAD

**Issue by WanderMax** [chinese-poetry/chinese-poetry#17]
例如 苏轼的简介

`苏轼：(1037-1101)北宋文学家、书画家。字子瞻，号东坡居士，眉州             眉山（今属四川）人。苏洵子。嘉佑进士。神宗时曾任祠部员外郎，因 反对王安石新法而求外职，任杭州通判，知密州、徐州、湖州。后以作 诗“谤讪朝廷”罪贬黄州。哲宗时任翰林学士，曾出知杭州、颖州等，             官至礼部尚书。后又贬谪惠州、儋州。北还后第二年病死常州 。南宋 时追谥文忠。与父洵弟辙，合称“三苏”。在政治上属于旧党，但也有改革弊政的要求。其文汪洋恣肆，明白畅达，为“唐宋八大家”之一             。其诗清新豪健，善用夸张比喻，在艺术表现方面独具风格。少数诗篇 也能反映民间疾苦，指责统治者的奢侈骄纵。词开豪放一派，对后代很 有影响。《念奴娇・赤壁怀古》、《水调歌头・丙辰中秋》传诵甚广。             擅长行书、楷书，取法李邕、徐浩、颜真卿、杨凝式，而能自创新意。 用笔丰腴跌宕，有天真烂漫之趣。与蔡襄、黄庭坚、米芾并称“宋四家 ”。能画竹，学文同，也喜作枯木怪石。论画主张“神似”，认为“论             画以形似，见与儿童邻”；高度评价“诗中有画，画中有诗”的艺术 造诣。诗文有《东坡七集》等。存世书迹有《答谢民师论文帖》、《 祭黄几道文》、《前赤壁赋》、《黄州寒食诗帖》等。画迹有《枯木怪石图》、《竹石图》等。--(1037―1101)字子瞻，号东坡居士。眉州眉山(今属四川)人。苏洵长子。嘉二年(1057)进士。累除中书舍人、翰林学士、　端明殿学士、礼部尚书。曾通判杭州，知密州、徐州、湖州、颍州等。元丰三年(1080)以谤新法贬谪黄州。绍圣初，又贬惠州、儋州。徽宗立，赦还。卒于常州。追谥文忠。博学多才，善文，工诗词，书画俱佳。于词“豪放，不喜剪裁以就声律”，题材丰富，意境开阔，突破晚唐五代和宋初以来“词为艳科”的传统樊篱，以诗为词，开创豪放清旷一派，对后世产生巨大影响。代表作有　《念奴娇・赤壁怀古》、《江神子・猎主要作品有:定风波（莫听穿林打叶声）昭君怨（谁作桓伊三弄）洞仙歌（冰肌玉骨）浣溪沙（游蕲水清泉寺）西江月（顷在黄州）八声甘州・寄参寥子浣溪沙（簌簌衣巾落枣花）水龙吟（似花还似非花）行香子・过七里滩永遇乐（彭城夜宿燕子楼）西江月・重九（点点楼头细雨）满江红（江汉西来）满江红・怀子由作（清颍东流）江城子（十年生死两茫茫）念奴娇・赤壁怀古②临江仙（夜饮东坡醒复醉）水调歌头（明月几时有）蝶恋花（花褪残红青杏小）鹧鸪天（林断山明竹隐墙）望江南（春未老）卜算子（缺月挂疏桐）贺新郎（乳燕飞华屋）阮郎归（绿槐高柳咽新蝉）`

1037―1101 这部分就是重复的开头

**Comment by jackeyGao** [comment]
对的， 是有这个问题， 中间有‘--’分割， 是两个不同版本的作者描述。 如果仔细观察会发现两个还是有区别的，后半部分有点出注明的作品集。

可以针对不同场景使用. 比如在词详细页， 作者信息提供第一个版本.   作者介绍页提供第二个版本.

**Comment by WanderMax** [comment]
发现了, 部分有这种情况, 部分却没有, 短简介不少存在截断错误, 比如在句中就截断了.
抓取的那个网站我也找到了, 抓取不易!
