### ISSUE TITLE
建议增加毛泽东诗词

### ISSUE THREAD

**Issue by luzwales** [chinese-poetry/chinese-poetry#172]
毛泽东诗词是中国古诗词的另一个高峰，建议加一下！

**Comment by EtherDream** [comment]
还有林则徐的诗也很不错

**Comment by MingliangLu** [comment]
不想活了？

**Comment by JMbaozi** [comment]
毛泽东诗词可以直接另开

**Comment by cheetosysst** [comment]
歷史來說是挺重要，詩詞上的高峰就尷尬了:smile:

**Comment by WangHaiYang874** [comment]
> 
> 
> 歷史來說是挺重要，詩詞上的高峰就尷尬了😄


帝王气象的诗人可就毛主席一个啊，算得上一座高峰了。蒋介石当年号召文人作诗《沁园春·雪》可都是没一个人能比得上的，从这点看，一个时代的诗词高峰也不是虚言。

**Comment by Aquarian-Age** [comment]
毛某人什么时候成古人了？

**Comment by jackeyGao** [comment]
老铁们， 暂时不要讨论这个人物了。    大家新年快乐！

**Comment by xinjiajuan** [comment]
毛的诗怎么说也和你仓库标题沾点边吧，为什么不能加上呢？
