### ISSUE TITLE
如何把高频词云图做成数据列表？

### ISSUE THREAD

**Issue by steveyang331** [chinese-poetry/chinese-poetry#176]
我看到高频词有云图，但没有高频词的数据列表。如果能做出数据表。就可以通过高频词加上作者以及历史背景比较准确的得出，古人在那个年代最关心的什么问题？为什么会关心这些问题？表达了什么问题？与我们当今词频可以做对比？我们当下高频词关心什么问题？为什么当今关心这些问题？等等

从云图来看，何处，人间。词频最高。这明显是人类终极追问的哲学。
我来自哪里？我是谁？我要到哪里去？
空间追问，时间追问，人类追问。

从词频数据来看，应该可以看出不同年代词频发生的细小变化，但没有详细数据列表，不太好分析。

而且我认为词频数据分析，应该是这个中国古诗词最重大的作用价值之一。

当然最好能够自定义给出词频词频关键字。然后很可能对他进行分类。比如 地点，人物，时间，情感，词性（名词，形容词）等等 归类词频数据

**Comment by jackeyGao** [comment]
首先分词就有大问题， 目前的分词大部分采用现代语义， 不能很好的支持古文。

**Comment by swuecho** [comment]
> 首先分词就有大问题， 目前的分词大部分采用现代语义， 不能很好的支持古文。

分词的话，找古文的语料去训练就好了。

**Comment by steveyang331** [comment]
> 首先分词就有大问题， 目前的分词大部分采用现代语义， 不能很好的支持古文。

可能我不懂，我设想的是 指定某个词语进行 词频统计。比如指定“人间”这个词，然后统计出“人间”这个词在诗歌中出现多少次。就像 excel那样操作嘛。

**Comment by jackeyGao** [comment]
@steveyang331 可以看下"jieba 分词” 文档， 分词对古文支持不好。 可以看出那些统计图上的词， 我们几乎都能很容易理解。

**Comment by steveyang331** [comment]
> @steveyang331 可以看下"jieba 分词” 文档， 分词对古文支持不好。 可以看出那些统计图上的词， 我们几乎都能很容易理解。

非常感谢，找到 结巴分词了。其实我是想借古诗词，分词之事用于其他中文文档分词。

**Comment by qq475742653** [comment]
关于结巴分词，需要获取到中华汉语词典，自定义词典库去分词。看我做的网站，里面有个分词注解的功能。
htttps://www.headset.xin/tangsongsc

**Comment by qq475742653** [comment]
高频词云图也有哦。我这个词频是统计了将近80万首诗词中获取的。
