### ISSUE TITLE
古诗词分词

### ISSUE THREAD

**Issue by Himoriarty** [chinese-poetry/chinese-poetry#18]
作者是如何对这些诗句分词的，是自己训练的还是用已有的模型，是否可以推荐比较准确的诗句分词模型

**Comment by jackeyGao** [comment]
README.md 中的高频词图（作者图是根据统计得出），只是用了默认（没有自定义词典的情况下）的jieba分词，所以对古文中分词操作，作用的很不规范。 我也很期待， 有这样的模型或词典。
