### ISSUE TITLE
能增加易经的数据么

### ISSUE THREAD

**Issue by LuckyFishGeek** [chinese-poetry/chinese-poetry#19]
能增加易经的数据么

**Comment by jackeyGao** [comment]
可以  古典文集都非常欢迎， 您有可靠的采集点吗?

**Comment by EastwindZL** [comment]
@jackeyGao 我去找找，然后发给您审核下，觉得可以再发布，感谢

**Comment by jackeyGao** [comment]
@EastwindZL  👍 非常感谢

**Comment by EastwindZL** [comment]
http://duyijing.cn/#!/   您看看这个网站 行不

**Comment by jackeyGao** [comment]
酷， 这个我完全看不懂， 有时间可以讨论下字段怎么存储吗？

**Comment by jtian0** [comment]
此 issue 已经超出 repo 话题范围，如果 owner 有意扩展话题，能不能在 wiki 整理/存档这些已经涉及到的内容？

**Comment by FuGangqiang** [comment]
经书的话这个里面的质量比较高：[中国哲学书电子化计划](https://ctext.org/zhs)
