### ISSUE TITLE
发现一个小问题，某些json文件里并不是1000句诗词，有一两首的出入

### ISSUE THREAD

**Issue by smilevent** [chinese-poetry/chinese-poetry#195]
多的少的都有

/chinese-poetry/json/poet.tang.2000.json 1002
/chinese-poetry/json/poet.tang.3000.json 1001
/chinese-poetry/json/poet.tang.6000.json 1001
/chinese-poetry/json/poet.tang.7000.json 1003
/chinese-poetry/json/poet.tang.8000.json 1001
/chinese-poetry/json/poet.tang.18000.json 1001
/chinese-poetry/json/poet.tang.19000.json 1002
/chinese-poetry/json/poet.tang.20000.json 1002
/chinese-poetry/json/poet.tang.25000.json 1002
/chinese-poetry/json/poet.tang.32000.json 1001
/chinese-poetry/json/poet.tang.35000.json 1001
/chinese-poetry/json/poet.tang.37000.json 1001
/chinese-poetry/json/poet.tang.38000.json 1002
/chinese-poetry/json/poet.tang.39000.json 1001
/chinese-poetry/json/poet.tang.41000.json 1001
/chinese-poetry/json/poet.tang.44000.json 1001
/chinese-poetry/json/poet.tang.47000.json 1001
/chinese-poetry/json/poet.tang.50000.json 999
/chinese-poetry/json/poet.tang.51000.json 999
/chinese-poetry/json/poet.song.20000.json 1001
/chinese-poetry/json/poet.song.26000.json 1001
/chinese-poetry/json/poet.song.51000.json 1001
/chinese-poetry/json/poet.song.53000.json 1001
/chinese-poetry/json/poet.song.64000.json 1001
/chinese-poetry/json/poet.song.80000.json 1001
/chinese-poetry/json/poet.song.120000.json 1001
/chinese-poetry/json/poet.song.123000.json 1001
/chinese-poetry/json/poet.song.192000.json 1001
/chinese-poetry/json/poet.song.209000.json 1001
/chinese-poetry/json/poet.song.233000.json 1001

**Comment by jackeyGao** [comment]
这些是有过改动的， 如果认为缺少诗词增加诗词， 或者重复诗词去除诗词的， 一般都 merge 改掉了， 这个正常的。
