### ISSUE TITLE
幼学琼林卷一有错别字

### ISSUE THREAD

**Issue by cfeibiao** [chinese-poetry/chinese-poetry#198]
卷一天文
1.“雷部推車之女回阿香“应为"雷部推車之女曰阿香"
2.”不殊夸父追回“应为“不殊夸父追日”

卷一地舆
1.“日诞登道岸”应为“曰诞登道岸”
2.“爲学己大成”应为“爲学已大成”

**Comment by jackeyGao** [comment]
收到， 我有空修掉 ：）

**Comment by O70** [comment]
抱歉
