### ISSUE TITLE
可否提供简体版本？我用python转换的版本在细节上会存在问题

### ISSUE THREAD

**Issue by vincentcsl** [chinese-poetry/chinese-poetry#218]

**Comment by LiuPeiqi-CNHN** [comment]
我也出现这种问题，一个字可能对应多个繁体字和异体字，比如妝可以转为妆，但是粧和糚不可以转为妆。颜有顏顔，为有為爲，很多这种情况，不知道怎么解决。

**Comment by Liangchengdeye** [comment]
> 我也出现这种问题，一个字可能对应多个繁体字和异体字，比如妝可以转为妆，但是粧和糚不可以转为妆。颜有顏顔，为有為爲，很多这种情况，不知道怎么解决。

你是通过 ：[繁体转简体](https://blog.csdn.net/qq_39905917/article/details/90904786) 这种方式转换的吗，我也发现了你提到的问题。

**Comment by vincentcsl** [comment]
@Liangchengdeye 我是使用这个方法的

**Comment by Liangchengdeye** [comment]
> @Liangchengdeye我是使用这个方法的

作者没提供简体版本，但是可以自己转换，下载那个python文件后，修改zh_wiki.py文件中：在zh2Hans 字典中添加新的古体字便可实现。

**Comment by vincentcsl** [comment]
@Liangchengdeye 是的，谢谢
