### ISSUE TITLE
如果要全，那么其他朝代的诗词歌赋也不能少。

### ISSUE THREAD

**Issue by lonycc** [chinese-poetry/chinese-poetry#22]
屈原的《离骚》
汉高祖刘邦的《大风歌》
汉乐府诗《孔雀东南飞》
曹操、曹丕、曹植三父子的诗歌
建安七子的诗歌
竹林七贤的诗歌
东晋：陶渊明
南北朝：谢灵运、谢朓、颜延之、鲍照、庾信、沈约、江淹
乐府诗集《古诗十九首》
北朝民歌《木兰诗》
元明清三朝

[诗词名句](http://www.shicimingju.com/)

**Comment by jackeyGao** [comment]
是的， 有想法并在未来计划做《诗经》、《易经》或其它文集的收集。 同时欢迎已经采集好的数据 pr。 感谢！ 这两天突然 star 好多。。。

**Comment by bovink** [comment]
我是因为我的主页上某个有名的人2天前star了你们才知道这个repo的，我想应该有不少人是跟我一样的。

**Comment by jackeyGao** [comment]
@bovink 谢谢解答，因为上周这个时候还有700star左右， 我周六看到着实吓了 我一跳。  这更加让我相信自己做的事情是对的。

**Comment by phoenixgao** [comment]
请作者 @jackeyGao  看一下搜韵，我以前也爬过他们诗词。
https://sou-yun.com/
目前收录779,235首。

**Comment by jackeyGao** [comment]
已收藏这个平台， 不知道有没有版权，古诗词本没有了版权保护， 因为开源的缘故， 但二次创作的东西要考虑版权。 我会尽自己努力去完善这个文库。同时也会询问一些专业的法律人士， 来避免有版权纠纷。 感谢各位建议。

**Comment by phoenixgao** [comment]
另外分享一些我维护诗词库的经验，希望对您有帮助：
当文库越来越大的时候，就一定会涉及到多个来源，不同的网站，不同版本的古籍，不同的网友提交的PR，这些版本都可能有大量的字词互异，缺字，缺句，题异，顺序有异，句读划分不同等等，甚至同一首诗词作者不同。如何选择一个相对来说比较靠谱的版本作为信本，来保证这个诗词库的内容质量，可能就不是技术社区的能力所及了。如果有可能的话，找一些文献学、训诂学专业的朋友一起维护会更好。

**Comment by jackeyGao** [comment]
@phoenixgao 谢谢， 这几天也深深的感受到了。 总之不是一个简单的事情， 以后有困难请教 还望不吝赐教。

**Comment by Niutranser-Li** [comment]
好的 您提出的建议我已经收到 您的建议非常宝贵 我非常感激 会争取第一时间改进 以后我会陆续的发布一些优秀的深度学习项目 初期大部分都是基于Pytorch实现的 后期可能会假如一些tensorflow的项目 喜欢的话可以经常提出一些建设性的建议 我会认真查看哒 谢谢~~~~

在 2019-08-20 20:59:33，"tony" <notifications@github.com> 写道：


Closed #22.
