### ISSUE TITLE
建议更换采集源，或对采集源标注许可说明

### ISSUE THREAD

**Issue by duanyukai** [chinese-poetry/chinese-poetry#227]
根据爬虫介绍页可以发现，唐诗宋词数据基本来源于作文网，该网站http://qts.zww.cn/ 中有如下标注：
```
全唐诗校订来自于湖北人民出版社出版的《全唐诗》。唐诗诵读来自于湖北少年儿童出版社出版的《唐诗300首》。与此有关的版权由出版者所有。 
  本站内容用于非商业目的，非经许可，不准复制。
```
虽然全唐诗等内容本身应该无版权风险，但既然爬虫源站有相关说明，最好进行沟通后进行标注，也是对源站、原出版物工作的认可。并且，MIT协议也值的商榷。

**Comment by jackeyGao** [comment]
您好，版权问题此前 issue 有过讨论。 

以下为我个人的一些对您问题的回应和想法

- 宋词是的， 但唐诗和宋诗不是（它们是简体，这边是繁体， 而且唐诗比它网站上多）。
- 这种检索系统在很多网站（多出现于高校网站）上都有看到， 并且已经出现多个版本。《全唐诗》是清康熙四十四年， 现在出版社的版本我认为是基于此简体中文制作。
- 尊重而且不进行收录各种基于诗词演绎之后的数据成果（赏析， 朗读/评论， 翻译），但作品（诗词）本身已属于公有领域。
- MIT 协议仅针对本格式化数据  #76。
- 如有版权方告知侵权就删除， 目前暂未收到类似请求。
- 我初衷依然是古文数据化，让古风应用更快上线。 我不会独占此份数据库， 任何人都不能有此野心。 

版本问题不再回应。
