### ISSUE TITLE
赤壁重复？

### ISSUE THREAD

**Issue by Jack6811** [chinese-poetry/chinese-poetry#232]
在最近使用本项目时发现一首诗同内容，不同作者

|  id   | author  | title | paragraphs |  file |
|  ----  | ----  | ---- |----|----|
7c93c162-d424-4d91-b71b-7c9b81713b8c |	杜牧  | 赤壁 | [ "折戟沈沙鐵未銷，自將磨洗認前朝。", "東風不與周郎便，銅雀春深鏁二喬。" ] | poet.tang.28000.json |
ae660471-84bc-4a58-a438-005b8a99c3c1 | 李商隐 | 赤壁 | [ "折戟沈沙鐵未銷，自將磨洗認前朝。", "東風不與周郎便，銅雀春深鏁二喬。" ] | poet.tang.29000.json |

据我所知赤壁是杜牧的啊，怎么回有两个一样的呢？

**Comment by jackeyGao** [comment]
基于搜索的结果我猜测是小李杜时期相近， 并且出现了多个信息源（当时流传的诗词集）都有记录， 当时编著者和当时所处的学界并不确定真正的作者。全唐诗编著的时会把争议的古诗都会保留， 所以会出现重复。 

很多 issue 都反馈数据有问题， 很遗憾这是一份不很正确的数据， 随着历史的研究，除了重复还有很多其他问题暴露出来， 包括字句的变动，字体的变动， 作者的变动。
