### ISSUE TITLE
请问作者诗json数据中能够表明作者是属于宋代还是唐代吗？

### ISSUE THREAD

**Issue by KomaBeyond** [chinese-poetry/chinese-poetry#25]
如题，如果可以的话还请作者在原数据中标注一下．
多谢

**Comment by jackeyGao** [comment]
诗的作者分为两个文件， 分别对于唐代和宋代。

https://github.com/chinese-poetry/chinese-poetry/blob/master/json/authors.tang.json 这里对应唐诗的作者， 所有全唐诗的作者在这个文件。

https://github.com/chinese-poetry/chinese-poetry/blob/master/json/authors.song.json 这里是对应宋诗的作者。

**Comment by KomaBeyond** [comment]
嗯，我知道你这个作者的结构，这个没问题．
我现在是说那些诗的json数据，比如里面有一首诗的作者是＂于觀文＂，这个名字在唐代和宋代都有，那么对应这首诗的作者到底是唐代那个人还是宋代那个人，这就不知道了．

**Comment by KomaBeyond** [comment]
抱歉．才看到，你的诗的数据也分了唐宋．．．，通过文件名可以区分，谢谢作者，辛苦

**Comment by jackeyGao** [comment]
这个可能是作者跨了朝代，  全唐诗和宋诗都有他的作品。  网上大多给他定为宋代诗人。

还有一种情况是重名

比如

```
authors.song.json:    "name": "王初",
authors.song.json:    "desc": "王初，建州甌寧（今福建建甌）人。仁宗天聖二年（一○二四）進士（明嘉靖《建寧府志》卷一五）。有《王初歌詩集》一卷（《直齋書錄解題》卷二○），已佚。今錄詩十二首。"
authors.tang.json:    "name": "王初",
authors.tang.json:    "desc": "王初，幷州人，仲舒之長子也。元和末，登進士第。詩十九首。"
```

**Comment by KomaBeyond** [comment]
还有一个问题，请问下你能拿到每首诗的创作时间吗？

**Comment by jackeyGao** [comment]
Sorry， 这个拿不到

**Comment by KomaBeyond** [comment]
OK，多谢了，你这个我觉得蛮有价值，我在基于你这个整理一份mysql形式的数据文件，这样作为基础数据使用会更加方便些

**Comment by jackeyGao** [comment]
很期待， 这个需求很强烈  😀

**Comment by KomaBeyond** [comment]
嗯，脚本我正在弄了，好了提pr给你

**Comment by jackeyGao** [comment]
我的建议是单独弄出来一个仓库， 这里只做文本数据源的存储，方便以后更新。你那边也可以直接同步更新 dump.sql.  我会在 readme.md 做引用。

**Comment by KomaBeyond** [comment]
也OK，那我搞好之后在这儿发个链接给你咯

**Comment by KomaBeyond** [comment]
mysql 数据格式仓库地址：https://github.com/KomaBeyond/chinese-poetry-mysql

**Comment by jackeyGao** [comment]
@KomaBeyond  感谢此份数据， README.md 更新了。
