### ISSUE TITLE
yuanqu.json不是合法的json格式

### ISSUE THREAD

**Issue by Sloaix** [chinese-poetry/chinese-poetry#256]
我理解开发者的意图,应该是为了方便按行解析,避免一次性把整个文本读入内存,所以元曲的每一行都是标准的json obect,但是最后一行多了一个中括号,会导致解析失败.

```json
{"dynasty":"yuan","author":"邵亨贞","paragraphs":["谁写江南一段秋，妆点钱塘苏小楼？楼中多少愁！楚山无断头。"],"title":"越调・凭阑人题曹云西翁赠妓小画"}
]
```
如果是为了按行解析,那么不建议使用`json`作为后缀

**Comment by Sloaix** [comment]
建议在修复格式错误后,把`yunqu.json`重命名为`yuanqu.txt`

**Comment by jackeyGao** [comment]
这个地方之前是好的， 最近出现了JSON格式问题。 我会找时间修掉。
