### ISSUE TITLE
有没有中文简体版本的

### ISSUE THREAD

**Issue by WillZWL** [chinese-poetry/chinese-poetry#31]

**Comment by chenyuntc** [comment]
我写过一个脚本, 将唐诗部分的繁体转成简体的

https://github.com/chenyuntc/pytorch-book/blob/master/chapter9-神经网络写诗(CharRNN)/tranditional2simplified.sh  

需要先安装  [cconv](https://github.com/xiaoyjy/cconv)

**Comment by csrgxtu** [comment]
可以使用google translate将繁体批量转化为简体。

**Comment by jackeyGao** [comment]
后续会维护个简体中文版， 使用https://github.com/gumblex/zhconv做转换。

https://github.com/chinese-poetry/chinese-poetry-zhCN

**Comment by htchaan** [comment]
@jackeyGao 不弄成繁簡並存嗎? 只做簡體得出來的數據會不同吧

**Comment by jackeyGao** [comment]
我在考虑要不要并存，其实繁简互转很容易做，目前只维护繁体，如果并存感觉太大太臃肿。大家有什么建议吗？

**Comment by animalize** [comment]
我觉得没必要弄简体，有些转换不是1对1的关系，硬转换会丢失一些信息，比如把**裏**转成**里**，把**乾**转成**干**。

一些通假字可能也有意义，比如簷和檐，也许某位诗人用前者表示竹子盖的房檐，用后者表示木头盖的房檐。如果按百度搜索的转换规则把前者转成后者，也会丢失一些信息。

**Comment by KomaBeyond** [comment]
@jackeyGao README里面简体中文版仓库地址链接写错了啊

**Comment by jtian0** [comment]
建议关闭此 issue，各方理由总结如下：

- 高精度简繁转换很容易，现有的工具 [opencc](https://github.com/BYVoid/OpenCC)，[zhconv](https://github.com/gumblex/zhconv)
- 繁体 -> 简体并非一一对应，引起信息丢失
- 简繁体共存是数据源问题

**Comment by jackeyGao** [comment]
此issue关闭，如有需求 请参考繁简批量转换脚本。   https://github.com/chinese-poetry/chinese-poetry-zhCN/blob/master/trans.py    感谢 @animalize @jtian0 同学的建议。
