### ISSUE TITLE
請問《御定全唐詩》數據是否出錯

### ISSUE THREAD

**Issue by zebraft** [chinese-poetry/chinese-poetry#338]
我發現《御定全唐詩》json中“paragraphs”經常出現詩句不全現象，想請問，是否有可能是數據某一次轉換時，系統地漏掉了一些內容？

用diff與其他版本比了一下，好嚇人。例如說這一段 參看卷/json837）：
"""
< 珠殿香輧倚翠棱寒棲吾道寄孫登豈應肘後終無分還如華頂清談夜因有新詩寄鄭弘
< 一到涼泉未擬歸迸珠噴玉落階墀幾多僧只因泉在青山看著不可上多病多慵爭奈伊
< 夫差昏暗霸圖傾千古淒涼地不靈妖豔恩餘宮露濁此是前車況非遠六朝何更不惺惺
< 得罪唯驚恩未酬夷陵山水稱閒遊人如八凱須當國因人好寄新詩好不獨江東有沃州
< 一宿蘭堂接上才白雪歸去幾裴回黛青峰朵孤吟後明朝江上空回首始覺清風不可陪
< 文章國器盡琅玕朝騎駸駸歲欲殘彩筆只宜天上用翰苑舊知憑與說紫金輪畔寄書難
< 一別旌旗已一年二林真子勸安禪常思雙戟華堂裏自憐酷似隨陽雁霜打風飄到日邊
< 一聽玄音下竹亭卻思窗雪與囊螢只將清淨酬恩德不堪回首滄江上萬仞廬峰在杳冥
< 雨氣濛濛草滿庭式微吟劇更誰聽詩逢匠化唯貪住從茲還似歸回首唯祝台星與福星家在嚴陵釣渚旁細漣嘉樹拂窗涼難醫林藪煙霞癖終期金鼎調羹日再近尼丘日月光
< 溪木蕭條一憑闌玉霜飛後浪花寒釣魚船上風煙暝誰如太守分憂外時把西經盡日看
< 喜繼于悲錦水東還鄉仙騎卻尋嵩再燒良玉堯雲動他年必立吾君側好把書紳答至公
< 雪壓千峰橫枕上窮困雖多還激壯看師逸跡兩相宜江樓曾見落星石幾回試發將軍炮別有寒雕掠絕壁好文天子揮宸翰禦制本多推玉案晨開水殿教題壁唯師草聖藝偏高一掬山泉心便足
---
> 珠殿香輧倚翠棱寒棲吾道寄孫登豈應肘後終無分見說仙中亦有僧雲斂石泉飛險竇月明山鼠下枯藤還如華頂清談夜因有新詩寄鄭弘
> 一到涼泉未擬歸迸珠噴玉落階墀幾多僧只因泉在無限松如潑墨為雲塹含香啼鳥細茗甌擎乳落花遲青山看著不可上多病多慵爭奈伊
> 夫差昏暗霸圖傾千古淒涼地不靈妖豔恩餘宮露濁忠臣心苦海山青蕭條陵隴侵寒水仿佛樓臺出杳冥此是前車況非遠六朝何更不惺惺
> 得罪唯驚恩未酬夷陵山水稱閒遊人如八凱須當國猿到三聲不用愁花落扁舟香冉冉草侵公署雨修修因人好寄新詩好不獨江東有沃州
> 一宿蘭堂接上才白雪歸去幾裴回黛青峰朵孤吟後雪白猿兒必寄來簾卷茶煙縈墮葉月明棋子落深苔明朝江上空回首始覺清風不可陪
> 文章國器盡琅玕朝騎駸駸歲欲殘彩筆只宜天上用繡衣偏稱雪中看休驚斷雁離三楚漸入祥煙下七盤翰苑舊知憑與說紫金輪畔寄書難
> 一別旌旗已一年二林真子勸安禪常思雙戟華堂裏還似孤峰峭壁前步出林泉多吉夢帆侵分野入祥煙自憐酷似隨陽雁霜打風飄到日邊
> 一聽玄音下竹亭卻思窗雪與囊螢只將清淨酬恩德敢信文章有性靈夢曆山床聞鶴語吟思海月上沙汀不堪回首滄江上萬仞廬峰在杳冥
> 雨氣濛濛草滿庭式微吟劇更誰聽詩逢匠化唯貪住日覺恩深不易銘心苦只應消鬢黑夢遊頻入倚天青從茲還似歸回首唯祝台星與福星家在嚴陵釣渚旁細漣嘉樹拂窗涼難醫林藪煙霞癖又出芝蘭父母鄉孤帆好風千里暖深花黃鳥一聲長終期金鼎調羹日再近尼丘日月光
> 溪木蕭條一憑闌玉霜飛後浪花寒釣魚船上風煙暝古木林中砧杵幹至竟道心方始是空耽山色亦無端誰如太守分憂外時把西經盡日看
> 喜繼于悲錦水東還鄉仙騎卻尋嵩再燒良玉堯雲動方報深恩絳帳空遠道靈輀春欲盡亂山羸馬恨無窮他年必立吾君側好把書紳答至公
> 雪壓千峰橫枕上窮困雖多還激壯看師逸跡兩相宜高適歌行李白詩海上驚驅山猛燒吹斷狂煙著沙草江樓曾見落星石幾回試發將軍炮別有寒雕掠絕壁提上玄猿更生力又見吳中磨角來舞槊盤刀初觸擊好文天子揮宸翰禦制本多推玉案晨開水殿教題壁題罷紫衣親寵錫僧家愛詩自拘束僧家愛畫亦局促唯師草聖藝偏高一掬山泉心便足
40386,40390c40139,40143
"""

上文與下文，首尾是一樣的，但是中間就漏了好幾句。

再舉一例，劉禹錫名詩《送李庚先輩赴選》（「一家何啻十朱輪」），原詩8句56個字：
> 一家何啻十朱輪諸父雙飛秉大鈞曾脫素衣參幕客卻為精舍讀書人離筵雒水侵杯色征路函關向晚塵今日山公舊賓主知君不負帝城春

而本檔（卷/json359）則5句35個字，也是首尾無誤、中間給漏掉了：
< 一家何啻十朱輪諸父雙飛秉大鈞曾脫素衣參幕客今日山公舊賓主知君不負帝城春

即：
{
        "title": "送李庚先輩赴選",
        "author": "劉禹錫",
        "biography": "",
        "paragraphs": [
            "一家何啻十朱輪，諸父雙飛秉大鈞。曾脫素衣參幕客，",
            "今日山公舊賓主，知君不負帝城春。"
        ],
        "notes": [
            ""
        ],
        "volume": "卷三百五十九",
        "no#": 58
    },

其實這個檔案“paragraphs”好多7個句子的，明明不對，所以才想問，有沒有可能是技術上的問題所產生，有辦法從以前的版本恢復？

**Comment by jackeyGao** [comment]
@zebraft 即便是最初的内容也有不对的情况

**Comment by zebraft** [comment]
感謝 @jackeyGao , @CanvaChen 的說明🙏

那我的理解是，要使用這裡的全唐詩資料，應該用「全唐詩」裡的poet.tang.*.json數據，不要使用「御定全唐詩」的。
