### ISSUE TITLE
json文件后面的数字是什么意思？

### ISSUE THREAD

**Issue by zhanyuzhang** [chinese-poetry/chinese-poetry#39]
比如`poet.tang.54000.json`，54000有什么意义的？

**Comment by jackeyGao** [comment]
是作为分割文件的标识， 每1000首诗存为一个文件。

**Comment by zhanyuzhang** [comment]
那这种排序是有规律的吗？比如，我想做一个唐诗检索页面，要用什么方法检索才能提高速度 ？

**Comment by jackeyGao** [comment]
这个数字随着章节增长的， poet.tang.0.json是第一章节的内容， poet.tang.$.json 最后一个则是最后章节的内容。 比较遗憾古诗字段没有记录所在书籍的章节号。
