### ISSUE TITLE
有没有可能在json里加入诗词的创作时间或者类别？

### ISSUE THREAD

**Issue by Song-s-z** [chinese-poetry/chinese-poetry#40]
谢谢作者，对古文化贡献很大啊 。

**Comment by jackeyGao** [comment]
谢谢， 创作时间暂时没有计划， 但是类别标签已经开始做了。
https://github.com/chinese-poetry/chinese-poetry/issues/30

**Comment by Song-s-z** [comment]
请问，有类别标签的json文件大概什么时候可以得到呢？

**Comment by jackeyGao** [comment]
@Song-s-z 顺利的话是本周末可以做完一个能用的版本， 不过我觉得这是一个持续完善的过程。 标签请关注 #30 。

**Comment by jackeyGao** [comment]
已完成首版可用 https://github.com/chinese-poetry/chinese-poetry/commit/3153310e34fbd8a0b288f6e7207a541bb5b0ded3
