### ISSUE TITLE
错误数据/重复数据问题

### ISSUE THREAD

**Issue by snowtraces** [chinese-poetry/chinese-poetry#54]
应该是是源的问题
1. OCR结果未仔细校验，如唐诗【和蘇員外寓直】内容是 【-329-。】
2. 乐府类的全部重复了，如同事存在李白的两篇【鼓吹曲辭 上之回】、【上之回】，显然是一篇

**Comment by jackeyGao** [comment]
欢迎PR

**Comment by snowtraces** [comment]
【鼓吹曲辭 上之回】、【上之回】这种在各个版本的全唐诗中都是重复录入的。写了个web ，实现了搜索，繁简切换
http://poetry.xinyo.org/poetry/281747
https://github.com/snowtraces/poetry-web

**Comment by jackeyGao** [comment]
@snowtraces  页面很赞 👍  我看了下「鼓吹曲辭 上之回」 出现https://github.com/chinese-poetry/chinese-poetry/blob/master/json/poet.tang.0.json的三个地方， 分别是[L14100](https://github.com/chinese-poetry/chinese-poetry/blob/master/json/poet.tang.0.json#L14100), [L14129](https://github.com/chinese-poetry/chinese-poetry/blob/master/json/poet.tang.0.json#L14129), [L14147](https://github.com/chinese-poetry/chinese-poetry/blob/master/json/poet.tang.0.json#L14147). 虽然这三处唐诗标题一样， 但是内容不一样， 不确实是表现手法还是错误的修订。

**Comment by snowtraces** [comment]
@jackeyGao  我指的是这种重复，全唐诗编撰的时候本身是重复的
http://localhost:8080/poetry/search?keyword=%E4%B8%89%E5%8D%81%E5%85%AD%E9%9B%A2%E5%AE%AE&page=1

**Comment by jackeyGao** [comment]
是有这种情况发生的， 而且还有其他错误， 包括错别字，生僻字，重复等， 如果确定是错误的， 并知道符合现代的表现方式， 可以提交 pr 修改。  谢谢兄弟

**Comment by snowtraces** [comment]
贴错了地址
http://poetry.xinyo.org/poetry/search?keyword=%E4%B8%89%E5%8D%81%E5%85%AD%E7%A6%BB%E5%AE%AB&page=1

**Comment by jackeyGao** [comment]
这个的确是源的问题， 这种问题在处理的时候， 也是小心翼翼。  暂时先记录吧。

https://github.com/chinese-poetry/chinese-poetry/blob/master/json/poet.tang.0.json#L14105
https://github.com/chinese-poetry/chinese-poetry/blob/master/json/poet.tang.8000.json#L1386

重复诗词

```json
{
    "author": "李白", 
    "paragraphs": [
      "三十六離宮，樓臺與天通。", 
      "閣道步行月，美人愁烟空。", 
      "恩疎寵不及，桃李傷春風。", 
      "淫樂意何極，金輿向回中。", 
      "萬乘出黃道，千旗揚彩虹。", 
      "前軍細柳北，後騎甘泉東。", 
      "豈問渭川老，寧邀襄野童。", 
      "但慕瑤池宴，歸來樂未窮。"
    ], 
    "strains": [
      "○仄仄○平，平平仄平平。", 
      "仄仄仄○仄，仄平平平○。", 
      "平○仄仄仄，平仄平平平。", 
      "平仄仄平仄，平平仄○○。", 
      "仄○仄平仄，平平平仄○。", 
      "平平仄仄仄，仄○平平平。", 
      "仄仄仄平仄，平平平仄平。", 
      "仄仄平平仄，平平仄仄平。"
    ], 
    "tags": [
      "忧国忧民", 
      "鼓吹曲辞", 
      "乐府"
    ], 
    "title": "上之回"
  }
```

**Comment by snowtraces** [comment]
还是保留着吧，全唐诗就是这样的

**Comment by weiyinfu** [comment]
重复现象非常多，大约几千首是重复的。
通过对诗句建立倒排索引，可以快速找到相似诗歌。

**Comment by snowtraces** [comment]
> 重复现象非常多，大约几千首是重复的。
> 通过对诗句建立倒排索引，可以快速找到相似诗歌。

全唐诗编撰本身就是重复的，所以没有去重

**Comment by animalize** [comment]
有些重复的诗，其中的字、词略有不同，似乎是从不同渠道搜集的。
