### ISSUE TITLE
《论语》数据库

### ISSUE THREAD

**Issue by Ronghengzhen** [chinese-poetry/chinese-poetry#59]
没有人做论语数据库吗？感觉这个很酷啊。

**Comment by jackeyGao** [comment]
暂时还没有， 期待 PR

**Comment by quzhi1** [comment]
原来写过一个论语txt到json的parser，但是输出早就丢了，源码还在：https://github.com/quzhi1/ElasticSearchLiteratureAnalysis/blob/master/ElasticSearchPlay/src/com/literatureAnalysis/Analects.java

**Comment by jackeyGao** [comment]
论语数据已经有啦， 感谢 @wptoux 提供
https://github.com/chinese-poetry/chinese-poetry/blob/master/lunyu/lunyu.json
