### ISSUE TITLE
我之前做了一个自动写诗的机器人，想用这里的数据做一些改进和升级。

### ISSUE THREAD

**Issue by hjptriplebee** [chinese-poetry/chinese-poetry#67]
1. 所做的也是一个开源的项目，详见[这里](https://github.com/hjptriplebee/Chinese_poem_generator)，请问可以用这里的数据吗？

2. 如果能有一些和诗句对应的图片，我还想做看图写诗的功能，不知道这种数据有没有什么获取途径？

**Comment by jackeyGao** [comment]
**答:**
1.  欢迎使用  😀😀
2. 还不知道有什么平台可以提供这样的图片
