### ISSUE TITLE
问一下，为什么繁体字特别多呢？

### ISSUE THREAD

**Issue by juggkit** [chinese-poetry/chinese-poetry#69]
rt

**Comment by jackeyGao** [comment]
古诗全是繁体， 宋词是简体。 

https://github.com/chinese-poetry/chinese-poetry#%E6%95%B0%E6%8D%AE%E5%88%86%E5%8F%91%E5%BD%A2%E5%BC%8F

**Comment by smilevent** [comment]
不仔细看README文件哦
>古诗数据分发采用繁体字的分组JSON文件, 保留繁体能更大程度地保存原数据. 宋词数据分发采用sqlite数据库, 使用简体字(无原因, 采集源就是简体, 如需繁体请自行转换).
