### ISSUE TITLE
你好 宋词不完整 有的缺少一句或两句的

### ISSUE THREAD

**Issue by li914** [chinese-poetry/chinese-poetry#70]
你好 非常感谢你能够做这个项目  让我们能够拿来用 谢谢你 最近发现宋词不完整 有的缺少一句或两句的

**Comment by jackeyGao** [comment]
Hi 此数据为采集下来， 可能有缺陷的地方，

可以更具体的描述下吗？ 我们可以补充完善的。

**Comment by li914** [comment]
六么令·淡烟残照 缺少最后一句“好天良夕。鸳帷寂寞，算得也应暗相忆。 ”
迷神引·一叶扁舟轻帆卷 缺少最后两句	“芳草连空阔，残照满。佳人无消息，断云远。”

现在发现柳永的词 几乎有一半最后都缺一句两句的

**Comment by jackeyGao** [comment]
@li914 已确认！  抱歉哈，因为我的疏忽 ([BUG详情](https://gist.github.com/jackeyGao/d73381087b1278177aab60636f635119#file-crawl_songci_parse-py-L169)) ， 造成很大一部分宋词后两句没有采集到 🤣🤣。 我会在今天完善这份数据。

**Comment by jackeyGao** [comment]
欢迎使用 ， 缺句已经修复。😀

**Comment by animalize** [comment]
唐诗也有少量缺最后一句的，能修复一下吗？

**Comment by jackeyGao** [comment]
@animalize 这个是宋词采集的 BUG 导致所有的宋词缺少最后两句， 唐诗可能源数据已经缺少。 这个恐怕只能人为的补充了...
