### ISSUE TITLE
作者重复问题

### ISSUE THREAD

**Issue by buf1024** [chinese-poetry/chinese-poetry#79]
无意中发现这个项目，采用该项目的数据来写一个离线RN的手机客户端，地址：[hellopoet](https://github.com/buf1024/hellopoet)   

写好后发现有一部分作者重复了，比如作者秦观, 范仲淹：  
```
./json/authors.song.json:8555 秦觀  
./ci/author.song.json:68 秦观  

./ci/author.song.json:39:    "name": "范仲淹", 
./json/authors.song.json:2616:    "name": "范仲淹"
```
两处其实指的是同一个人，虽然简繁体字和desc部分稍微有不同。

**Comment by jackeyGao** [comment]
这种情况是有的， 此数据库诗词是分开的， json 里面是唐诗和宋诗， ci 目录里面是宋词。 秦观和范仲淹都是宋朝代诗人，诗词都有相应的作品记录。 而且应该不止这两位， 这种情况可以手动处理下。

**Comment by buf1024** [comment]
是的，不止这两位，我只是举两位作为例子。
OK，明白了，谢谢！
