### ISSUE TITLE
个人的一个网站使用了这个库的诗词数据，特地表示感谢，并且欢迎大家体验

### ISSUE THREAD

**Issue by eniumeng** [chinese-poetry/chinese-poetry#82]
timecoord.com

**Comment by eniumeng** [comment]
[timecoord.com](https://www.timecoord.com/?from=github)

**Comment by XAS-712** [comment]
这个。。。需要专门发issue吗。。。

**Comment by Ellldin** [comment]
Setting C Notification 下关闭 Participating 和 Watching 就可以了。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 0x10 <notifications@github.com>
发送时间: Monday, October 1, 2018 9:33:18 PM
收件人: chinese-poetry/chinese-poetry
抄送: Subscribed
主题: Re: [chinese-poetry/chinese-poetry] 个人的一个网站使用了这个库的诗词数据，特地表示感谢，并且欢迎大家体验 (#82)


这个。。。需要专门发issue吗。。。

―
