### ISSUE TITLE
用数据库做了个微信小程序

### ISSUE THREAD

**Issue by Zhangcanpu** [chinese-poetry/chinese-poetry#87]
诗词百科全书  有需要得可以用一下 看看

**Comment by xjr7670** [comment]
被你抢先一步了，我本来也有这个想法的 😃

**Comment by li914** [comment]
这个也至于发个issues吗？？？

**Comment by xjr7670** [comment]
@Zhangcanpu 

能否发一下你的小程序二维码到我邮箱？我看看你做的效果怎么样的，如果能满足我的使用需求的话，我就不写了，谢谢，邮箱我资料里有（发在这里觉得有点骚扰别人的意思，又没法发私信）

**Comment by swuecho** [comment]
👍
可以在readme里面增添用到本数据集的开源程序。

**Comment by chengluyu** [comment]
Issue 不应该成为宣传的地方。
