### ISSUE TITLE
靜夜思 错误

### ISSUE THREAD

**Issue by swimfish09** [chinese-poetry/chinese-poetry#93]
![image](https://user-images.githubusercontent.com/3916975/50127720-444cea80-02ad-11e9-9155-71e62acba62c.png)
床前明月光，疑是地上霜
举头望明月，低头思故乡

**Comment by tylk520** [comment]
这是原始版本的 长点知识吧 现在流行的是明人的伪作。还有怒发冲冠满江红通篇系伪作，我们是托古言志（FaMingLiShi）的老祖宗
