### ISSUE TITLE
请问可以使用这个文本库做app吗？

### ISSUE THREAD

**Issue by zhaopuming** [chinese-poetry/chinese-poetry#98]
我想做一个阅读的app，其中有读古诗文的模块，我想使用chinese-poetry的文本库作为诗词数据来源，请问可以吗？

我的app打算做成全开源，地址是：<https://github.com/neostudy/neoreads>

现在还没开始做，将来打算公版书全免费，不打广告。不过未来可能会加上收费版权内容。

**Comment by jackeyGao** [comment]
欢迎使用，无任何约束😃

**Comment by zhaopuming** [comment]
谢谢，我会在每首诗加上来源说明 :-)
